export const TOGGLE_PAGE_LOADING = 'TOGGLE_PAGE_LOADING';
export const LOGOUT = 'LOGOUT';

export const FETCHING_USER_REPOS_REQUEST = 'FETCHING_USER_REPOS_REQUEST';
export const FETCHING_USER_REPOS_SUCCESS = 'FETCHING_USER_REPOS_SUCCESS';
export const FETCHING_USER_REPOS_FAILURE = 'FETCHING_USER_REPOS_FAILURE';

export const FETCHING_STARED_REPOS_REQUEST = 'FETCHING_STARED_REPOS_REQUEST';
export const FETCHING_STARED_REPOS_SUCCESS = 'FETCHING_STARED_REPOS_SUCCESS';
export const FETCHING_STARED_REPOS_FAILURE = 'FETCHING_STARED_REPOS_FAILURE';

export const SEARCHING_REPOS_REQUEST = 'SEARCHING_REPOS_REQUEST';
export const SEARCHING_REPOS_SUCCESS = 'SEARCHING_REPOS_SUCCESS';
export const SEARCHING_REPOS_FAILURE = 'SEARCHING_REPOS_FAILURE';

export const FETCHING_REPO_BASIC_REQUEST = 'FETCHING_REPO_BASIC_REQUEST';
export const FETCHING_REPO_BASIC_SUCCESS = 'FETCHING_REPO_BASIC_SUCCESS';
export const FETCHING_REPO_BASIC_FAILURE = 'FETCHING_REPO_BASIC_FAILURE';

export const FETCHING_REPO_README_REQUEST = 'FETCHING_REPO_README_REQUEST';
export const FETCHING_REPO_README_SUCCESS = 'FETCHING_REPO_README_SUCCESS';
export const FETCHING_REPO_README_FAILURE = 'FETCHING_REPO_README_FAILURE';

export const FETCHING_REPO_ISSUES_REQUEST = 'FETCHING_REPO_ISSUES_REQUEST';
export const FETCHING_REPO_ISSUES_SUCCESS = 'FETCHING_REPO_ISSUES_SUCCESS';
export const FETCHING_REPO_ISSUES_FAILURE = 'FETCHING_REPO_ISSUES_FAILURE';

export const FETCHING_REPO_LABELS_REQUEST = 'FETCHING_REPO_LABELS_REQUEST';
export const FETCHING_REPO_LABELS_SUCCESS = 'FETCHING_REPO_LABELS_SUCCESS';
export const FETCHING_REPO_LABELS_FAILURE = 'FETCHING_REPO_LABELS_FAILURE';

export const SEARCH_USERS_BY_NAME_REQUEST = 'SEARCH_USERS_BY_NAME_REQUEST';
export const SEARCH_USERS_BY_NAME_SUCCESS = 'SEARCH_USERS_BY_NAME_SUCCESS';
export const SEARCH_USERS_BY_NAME_FAILURE = 'SEARCH_USERS_BY_NAME_FAILURE';
