export const TOGGLE_PAGE_LOADING = 'TOGGLE_PAGE_LOADING';
export const LOGOUT = 'LOGOUT';

export const FETCHING_USER_REPOS_REQUEST = 'FETCHING_USER_REPOS_REQUEST';
export const FETCHING_USER_REPOS_SUCCESS = 'FETCHING_USER_REPOS_SUCCESS';
export const FETCHING_USER_REPOS_FAILURE = 'FETCHING_USER_REPOS_FAILURE';

export const FETCHING_STARED_REPOS_REQUEST = 'FETCHING_STARED_REPOS_REQUEST';
export const FETCHING_STARED_REPOS_SUCCESS = 'FETCHING_STARED_REPOS_SUCCESS';
export const FETCHING_STARED_REPOS_FAILURE = 'FETCHING_STARED_REPOS_FAILURE';
